version: "3.7"
services:
    django:
        build: .
        image: kinkgarden
        restart: unless-stopped
        environment:
            DEBUG: "true"
            ALLOWED_HOSTS: "127.0.0.1,localhost"
        ports:
            - "8000:8000"
        depends_on:
            - db
        networks:
            - main
        secrets:
            - secret-key
    db:
        image: postgres
        restart: unless-stopped
        environment:
            POSTGRES_HOST_AUTH_METHOD: trust
        volumes:
            - dbdata:/var/lib/postgresql/data
        networks:
            - main

volumes:
    dbdata:

networks:
    main:

secrets:
    secret-key:
        external: false
        name: kinkgarden-secret-key
        file: ./secrets/secret-key
