# Generated by Django 2.1.5 on 2019-01-28 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kink',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
