# Generated by Django 2.1.5 on 2019-01-29 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kinks", "0003_auto_20190128_1730"),
    ]

    operations = [
        migrations.AddField(
            model_name="kink", name="custom", field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="kink", name="name", field=models.CharField(max_length=200),
        ),
    ]
