# Generated by Django 2.2.4 on 2019-08-13 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinks', '0004_auto_20190128_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kink',
            name='custom',
        ),
    ]
