# Generated by Django 3.1 on 2020-08-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kinks", "0007_auto_20200811_2203"),
    ]

    operations = [
        migrations.AddField(
            model_name="kinklist",
            name="short_link",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
