# Generated by Django 3.1.1 on 2020-09-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kinks", "0009_kink_list_entry_verbose_name_plural"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomReject",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.RemoveField(model_name="customkinklistentry", name="admin_delete",),
    ]
